import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Mail, Lock, Loader2 } from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';

export default function PublicSignIn(){
  const { login } = useAuth();
  const [email,setEmail]=useState('demo@olitech.com'); const [password,setPassword]=useState('demo123'); const [remember,setRemember]=useState(true); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{await login(email,password); if(remember)localStorage.setItem('olitech_remember','1');}catch(err){setError(err.message||'Unable to sign in.');}finally{setLoading(false);}};
  return <div className="min-h-screen grid lg:grid-cols-2 bg-[#F5F3EF]">
    <div className="bg-[#090C11] text-white p-8 md:p-14 flex flex-col justify-center order-2 lg:order-1"><div className="max-w-xl mx-auto"><Link to="/" className="flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#FFD300] text-[#090C11] font-black flex items-center justify-center">OT</span><span className="font-black">OliTechs</span></Link><h1 className="mt-14 text-4xl md:text-5xl font-black leading-tight">Run your hotel<br/><span className="text-[#FFD300]">from one place.</span></h1><p className="mt-4 text-[#D6D6D6] max-w-md">Room Planner, PMS, POS and billing in one operating system.</p><div className="mt-8 bg-white rounded-2xl p-5 text-[#090C11] shadow-xl"><p className="text-[10px] font-bold text-[#757B81]">REVENUE TODAY</p><p className="text-2xl font-black">KES 284,650</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="bg-[#F5F3EF] rounded-xl p-3 text-xs">Open Tables <b className="float-right">7</b></div><div className="bg-[#F5F3EF] rounded-xl p-3 text-xs">Covers <b className="float-right">42</b></div></div><div className="mt-3 bg-[#FFD300] text-[#090C11] font-bold text-center py-3 rounded-xl text-xs">Open POS → Floor Plan</div></div></div></div>
    <div className="p-8 md:p-14 flex items-center order-1 lg:order-2"><div className="w-full max-w-[430px] mx-auto"><div className="bg-white rounded-2xl border border-[#E5E5E5] p-8 shadow-sm"><div className="w-9 h-9 rounded-xl bg-[#FFD300] text-[#090C11] font-black flex items-center justify-center">OT</div><h2 className="mt-5 text-2xl font-black">Welcome back</h2><p className="text-sm text-[#757B81] mt-1">Sign in to OliTechs PMS & POS</p>{error&&<div className="mt-5 p-3 rounded-xl bg-[#FFF0F0] text-[#D32F2F] text-sm">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-bold">Email<div className="relative mt-1"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#757B81]"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full h-12 border border-[#D6D6D6] rounded-xl pl-10 pr-4 outline-none focus:border-[#FFD300]"/></div></label><label className="block text-xs font-bold">Password<div className="relative mt-1"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#757B81]"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full h-12 border border-[#D6D6D6] rounded-xl pl-10 pr-4 outline-none focus:border-[#FFD300]"/></div></label><div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember me</label><Link to="/forgot-password" className="font-bold underline">Forgot password?</Link></div><button disabled={loading} className="w-full h-12 rounded-xl bg-[#090C11] text-white font-bold hover:bg-[#262B32]">{loading?<><Loader2 className="inline w-4 h-4 mr-2 animate-spin"/>Signing in...</>:'Sign In'}</button><div className="bg-[#F5F3EF] rounded-xl p-3 text-[11px] text-[#757B81]">Demo credentials: <b>demo@olitech.com / demo123</b></div><p className="text-center text-xs">No account? <Link to="/signup" className="font-bold underline">Start 7-Day Free Trial</Link></p></form></div><p className="text-center text-[11px] mt-4 text-[#757B81]">Designed by <a href="https://wa.me/254745043121" className="font-bold text-[#090C11]">Shadrack • +254745043121</a></p></div></div>
  </div>;
}
