import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Check,Hotel,User,Mail,Phone,Lock,Loader2} from 'lucide-react';
import {useAuth} from '@/lib/AuthContext';

export default function PublicSignUp(){
 const {register}=useAuth(); const [form,setForm]=useState({hotel:'',name:'',email:'',phone:'+254',password:'',confirm:''}); const [terms,setTerms]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [confirmation,setConfirmation]=useState(false);
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 const submit=async e=>{e.preventDefault();setError('');if(form.password!==form.confirm)return setError('Passwords do not match');if(form.password.length<6)return setError('Password must be at least 6 characters');if(!terms)return setError('Please agree to the Terms & Privacy.');setLoading(true);try{const r=await register({name:form.name,email:form.email,password:form.password,businessName:form.hotel});if(r?.needsEmailConfirmation)setConfirmation(true);localStorage.setItem('olitech_trial_started','1');}catch(err){setError(err.message||'Could not create your account.');}finally{setLoading(false)}};
 if(confirmation)return <div className="min-h-screen bg-[#F5F3EF] flex items-center justify-center p-6"><div className="max-w-md w-full bg-white border border-[#E5E5E5] rounded-2xl p-8 shadow-sm text-center"><div className="mx-auto w-12 h-12 rounded-xl bg-[#FFD300] text-[#090C11] flex items-center justify-center"><Mail/></div><h1 className="mt-5 text-2xl font-black">Check your email</h1><p className="mt-2 text-sm text-[#757B81]">We sent a confirmation link to {form.email}. Your 7-day trial application is ready and will remain pending until your property is approved.</p><Link to="/signin" className="mt-6 inline-block bg-[#090C11] text-white font-bold px-6 py-3 rounded-xl">Go to Sign In</Link></div></div>;
 const fields=[['hotel','Hotel Name',Hotel,'OliTechs Grand Hotel'],['name','Your Name',User,'Amina Kariuki'],['email','Email',Mail,'amina@hotel.com'],['phone','Phone',Phone,'+254745043121'],['password','Password',Lock,'••••••••'],['confirm','Confirm Password',Lock,'••••••••']];
 return <div className="min-h-screen grid lg:grid-cols-2 bg-[#F5F3EF]"><div className="bg-[#090C11] text-white p-8 md:p-14 flex flex-col justify-between"><div><Link to="/" className="flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#FFD300] text-[#090C11] font-black flex items-center justify-center">OT</span><span className="font-black">OliTechs</span></Link><h1 className="mt-16 text-4xl font-black leading-tight">Start your<br/><span className="text-[#FFD300]">7-day free trial.</span></h1><ul className="mt-8 space-y-4 text-sm">{['Full access to Room Planner, PMS & POS','5 rooms • 1 user • No credit card','Setup in 5 mins • Cancel anytime','M-Pesa, Card, Cash, Charge to Room'].map(x=><li key={x} className="flex gap-3 items-center"><span className="w-6 h-6 shrink-0 rounded-full bg-[#FFD300] text-[#090C11] flex items-center justify-center font-bold"><Check className="w-4 h-4"/></span>{x}</li>)}</ul><div className="mt-10 bg-[#262B32] rounded-2xl p-4 border border-white/10"><p className="text-xs text-[#D6D6D6] font-bold">ROOM PLANNER PREVIEW</p><div className="mt-3 grid grid-cols-4 gap-2"><div className="h-9 bg-[#090C11] rounded border-l-4 border-[#FFD300] text-[9px] px-2 flex items-center">Fully Paid</div><div className="h-9 bg-[#FFD300] text-[#090C11] font-bold rounded text-[9px] px-2 flex items-center">Partial</div><div className="h-9 bg-[#757B81] rounded text-[9px] px-2 flex items-center">Not Paid</div><div className="h-9 bg-[#333533] rounded text-[9px] px-2 flex items-center text-[#D6D6D6]">Room 204</div></div></div></div><p className="text-xs text-[#757B81]">© 2026 OliTechs • <a href="https://wa.me/254745043121" className="text-[#FFD300]">Designed by Shadrack</a></p></div>
 <div className="p-8 md:p-14 flex items-center"><div className="w-full max-w-[480px] mx-auto"><div className="bg-white rounded-2xl border border-[#E5E5E5] p-8 shadow-sm"><h2 className="text-2xl font-black">Create your hotel account</h2><p className="text-sm text-[#757B81] mt-1">Free for 7 days, then KES 7,500/mo. Cancel anytime.</p>{error&&<div className="mt-5 p-3 rounded-xl bg-[#FFF0F0] text-[#D32F2F] text-sm">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4">{fields.map(([k,label,Icon,placeholder])=><label key={k} className={`${k==='email'||k==='phone'?'':'block'} text-xs font-bold`}>{label}<div className="relative mt-1"><Icon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#757B81]"/><input required type={k==='password'||k==='confirm'?'password':k==='email'?'email':'text'} value={form[k]} onChange={e=>update(k,e.target.value)} placeholder={placeholder} className="w-full h-12 border border-[#D6D6D6] rounded-xl pl-10 pr-4 outline-none focus:border-[#FFD300]"/></div></label>)}<label className="flex gap-2 text-xs items-start"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} className="mt-0.5"/> I agree to Terms & Privacy</label><button disabled={loading} className="w-full bg-[#FFD300] text-[#090C11] font-bold py-3.5 rounded-xl hover:bg-[#FFD100]">{loading?<><Loader2 className="inline w-4 h-4 mr-2 animate-spin"/>Creating account...</>:'Start My 7-Day Free Trial'}</button><div className="flex items-center gap-3 text-xs text-[#757B81]"><span className="h-px flex-1 bg-[#E5E5E5]"/><span>or</span><span className="h-px flex-1 bg-[#E5E5E5]"/></div><p className="text-center text-xs">Already have an account? <Link to="/signin" className="font-bold underline">Sign In</Link></p></form></div><p className="text-center text-[11px] text-[#757B81] mt-4">No credit card • Cancel anytime • Setup in 5 mins</p></div></div></div>;
}
